### ISSUE TITLE
Publish device/sensor events and logs to pub/sub system

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-IoT#5]
This will be useful for debugging the system and will also give an insight into the otherwise blackbox system.

```[tasklist]
### Tasks
- [ ] Read the code and understand what needs to be changed and come up with an plan for implementation. Only the python module is involved in this currently.
- [ ] Catch all exceptions and errors wherever possible and parse them.
- [ ] Publish these as events with logs included as metadata to the pub/sub broker using Publisher, similar to the way other data is published.
```
